spring:
  application:
    name: "JobSearch"
  mvc:
    static-path-pattern: /static/**
  freemarker:
    expose-session-attributes: true

  datasource:
    url: jdbc:h2:./db/JobSearchDB;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver


#  sql:
#    init:
#      mode: always
  liquibase:
    change-log: classpath:/db/changelog/master.yml
  jpa:
    hibernate:
      ddl-auto: validate

#============================= Mail config

  mail:
    host: smtp.gmail.com
    username: izlax6002@gmail.com
    password: "sznj qgnx hsjj fyuz"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#============================= Mail config

  #============================ oAuth2.0 config
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: // GOOGLE SECRET_ID
            client-secret: // GOOGLE SECRET_KEY
            scope:
              - email
              - profile

#============================ oAuth2.0 config


logging:
  level:
    root: info
    org:
      springframework:
        security: debug
  file:
    path: logs
