spring:
  application:
    name: "Home_work_49"
  mvc:
    static-path-pattern: /static/**
  freemarker:
    expose-session-attributes: true
  datasource:
    url: jdbc:h2:./db/JobSearchDB;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always

  liquibase:
    change-log: classpath:/db/changelog/master.yml

logging:
  level:
    root: info
    org:
      springframework:
        security: debug
  file:
    path: logs
